<?php
/** @package Codeigtestuno::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("TbleventosMap.php");

/**
 * TbleventosDAO provides object-oriented access to the tbleventos table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Codeigtestuno::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class TbleventosDAO extends Phreezable
{
	/** @var string */
	public $Id;

	/** @var string */
	public $Nombre;


	/**
	 * Returns a dataset of ColegiosMovimientos objects with matching Idevento
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdeventoColegiosMovimientoss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "colegios_movimientos_ibfk_1", $criteria);
	}


}
?>